### ISSUE TITLE
Dynamic IP assignment to rina systems.

### ISSUE THREAD

**Issue by selvakumar8292** [IRATI/stack#1072]
How to assign dynamic ip address for the rina systems using shim-tcp-udp. Right now we are assigning a static ip address for systems and we are using that ip address in the shim-tcp-udp.dif configuration file. But if we want to change the ip address of a rina machine dynamically, without cancelling the ipcm terminal running the configuration at a terminal; how can we do that.

Please suggest an answer. Thanks in advance for your help.

**Comment by edugrasa** [comment]
Hi,

The best way would be to use domain names (instead of IP addresses) and DNS to update, but it is not in our development plans yet (we could provide some hints if you are intesested). 

Meanwhile I just merged in the `arcfire` branch this patch from Julien: https://github.com/IRATI/stack/pull/997/commits/a68a8ed0806769d879f99cf70883580620ebb4fa, maybe it is enough for what you want to do.

It can't be used yet because there is a bug in the shim-tcp-udp that crashes the kernel (after merging to arcfire), I'll fix it and tell you when all is ready to test.

**Comment by edugrasa** [comment]
Hi,

The bug on the shim-tcp-udp has been fixed in the 'arcfire' branch. Please beware that the installations instructions are now different, since we've modularized all of our kernel code. Now you first install Linux kernel 4.9 (currently this is the supported version) from the Linux repos, and after that install IRATI.
