### ISSUE TITLE
Add NLM_F_ACK in user-space

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#262]
<a href="https://github.com/lbergesio"><img src="https://avatars.githubusercontent.com/u/1797884?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [lbergesio](https://github.com/lbergesio)**
_Monday Jan 13, 2014 at 11:02 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/259_

----

In order to acknoledge the reception of a NL message by the kernel, user-space should add the NLM_F_ACK flag by default in all the messages sent to the kernel.

Kernel will autimatically send a  NLMSG_ERROR message with error_code = 0 upon reception.

User-space should receive this message and act consequently. For the time being log the event, and in the future react consequently if the error_code is != 0 and some action is required.

**Comment by sandervrijders** [comment]
@edugrasa Has this been done?

**Comment by edugrasa** [comment]
I don't think that doing this would bring any benefits. 

1) I've never seen a single NL message lost (it's just a syscall)
2) Even if this happened, we would notice an error anyway, since most messages require a response
3) Doing anything else than logging the message would mean we do retransmissions of NL messages?

**Comment by lbergesio** [comment]
This was a very old idea we had with @salvestrini . But I think it is not needed anymore due to Edu's second point and the fact that we have been using it log time without recognizing the need for this.

Moreover, according to the following, it would not make the interface 100% reliable anyway:

Netlink is not a reliable protocol. It tries its best to deliver a message to its destination(s), but may drop messages when an out-of-memory condition or other error occurs. For reliable transfer the sender can request an acknowledgement from the receiver by setting the NLM_F_ACK flag. An acknowledgment is an NLMSG_ERROR packet with the error field set to 0. The application must generate acknowledgements for received messages itself. The kernel tries to send an NLMSG_ERROR message for every failed packet. A user process should follow this convention too.

However, reliable transmissions from kernel to user are impossible in any case. The kernel can't send a netlink message if the socket buffer is full: the message will be dropped and the kernel and the user-space process will no longer have the same view of kernel state. It is up to the application to detect when this happens (via the ENOBUFS error returned by recvmsg(2)) and resynchronize.

**Comment by edugrasa** [comment]
Ok, closing then!
