### ISSUE TITLE
shim-eth-vlan cannot post SDUs whose size is less than 42

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#417]
<a href="https://github.com/vmaffione"><img src="https://avatars.githubusercontent.com/u/4920001?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [vmaffione](https://github.com/vmaffione)**
_Friday Nov 07, 2014 at 10:20 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/414_

----

When the Shim-eth-vlan receives an Ethernet frame and builds the corresponding PDU to post to the upper layers, the corresponding SDU to be delivered is always longer than 41 bytes (due to the minimum payload size of an Ethernet packet with a VLAN tag, which is 42 bytes).

**Comment by kewinrausch** [comment]
<a href="https://github.com/sandervrijders"><img src="https://avatars.githubusercontent.com/u/1212456?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sandervrijders](https://github.com/sandervrijders)**
_Friday Nov 07, 2014 at 10:41 GMT_

----

Why is this a bug? It's just the minimum size of an Ethernet payload.

**Comment by kewinrausch** [comment]
<a href="https://github.com/vmaffione"><img src="https://avatars.githubusercontent.com/u/4920001?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [vmaffione](https://github.com/vmaffione)**
_Friday Nov 07, 2014 at 14:07 GMT_

----

True, but the shim-eth-vlan should hide this constraint, and remove the padding - if possible.
That is, when you receive an ethernet frame, are you able to know the length of useful data (not including the padding)? If yes you should build an SDU that is as big as the useful data - and so less than 42 if it's the case. If not, I don't see a solution (apart from using fragmentation or TCP-like "stream" behaviour (no borders in data stream)).

**Comment by kewinrausch** [comment]
<a href="https://github.com/sandervrijders"><img src="https://avatars.githubusercontent.com/u/1212456?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sandervrijders](https://github.com/sandervrijders)**
_Friday Nov 07, 2014 at 14:09 GMT_

----

I don't think we should add it. It's not in Ethernet. It's a limitation of Ethernet and users of the shim DIF should hold this constraint into account when using it.

**Comment by kewinrausch** [comment]
<a href="https://github.com/sandervrijders"><img src="https://avatars.githubusercontent.com/u/1212456?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sandervrijders](https://github.com/sandervrijders)**
_Friday Nov 07, 2014 at 14:09 GMT_

----

Just like it does not support SDU sizes larger than 1500 bytes.

**Comment by kewinrausch** [comment]
<a href="https://github.com/vmaffione"><img src="https://avatars.githubusercontent.com/u/4920001?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [vmaffione](https://github.com/vmaffione)**
_Friday Nov 07, 2014 at 15:27 GMT_

----

Ok for applications running directly on shim-eth-vlan. But if you are an application running on normal DIF you want to be able to receive SDU of arbitrary lengths - e.g. 3 bytes. Since the normal DIF is using the shim-eth-vlan, should the normal DIF do the trick? Does it currently do it? Would it be possible?

**Comment by kewinrausch** [comment]
<a href="https://github.com/sandervrijders"><img src="https://avatars.githubusercontent.com/u/1212456?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sandervrijders](https://github.com/sandervrijders)**
_Friday Nov 07, 2014 at 18:25 GMT_

----

Yes, exactly, that's my point. This is not an issue of the shm-eth-vlan. Normal ipcp should add and strip the padding. Don't know if it currently does it. I wouldn't bet on it.

**Comment by kewinrausch** [comment]
<a href="https://github.com/edugrasa"><img src="https://avatars.githubusercontent.com/u/325005?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [edugrasa](https://github.com/edugrasa)**
_Friday Nov 07, 2014 at 19:22 GMT_

----

So one of the parameters of the DIF is also minimum accepted SDU size, right? Thinking about it, it makes sense... 

Well normal IPCP does still not care about maximum SDU size of N-1 DIF, imagine about the minimum ;) 
Yeah, all this should be considered.

**Comment by edugrasa** [comment]
This can be addressed by implemeting the delimiting policy (concatenation in #761). Closing this issue

**Comment by dstaesse** [comment]
@edugrasa: no it can't... what if I want to send one sdu? This needs to be addressed in the shim with proper padding for runt frames.

**Comment by dstaesse** [comment]
Adding the nuance that it can be done there is some mTU  and MTU limit disseminated towards the upper DIF and the N+1 DIF is then responsible for padding towards the N-DIF. But either way, the shim needs to be augmented to solve it.

**Comment by edugrasa** [comment]
@dstaesse right, but the only way of doing it properly is to do it at the upper layer (N+1 DIF). 

Imagine IPCP A encrypts a PDU, and still is less than 46 bytes, then sends it to the shim who adds the padding. There is nothing in Ethernet that tells if there is padding in a frame and what is its length, therefore the shim at the other end just passes the payload of the Ethernet frame to the upper DIF, who tries to decrypt but fails (because it is trying to decrypt an encrypted PDU + the padding). 

The IPCP has to add the padding before encrypting, then the IPCP at the other end can decrypt and after that remove the padding (using the length field in the EFCP PDU). Therefore, should we open another issue to implement padding within the normal IPCP? (probably as part of SDU protection?)

**Comment by dstaesse** [comment]
Well, the correct function is for N-1 DIFs to advertise the minimum Transmission Unit to the N-DIF. Or will you hardcode the 46 byte mTU in the normal IPCP?
The other way is to add the padding and strip the padding in the shim itself.
I think the LLC shim doesn't have this issue (it has a length field instead of Ethertype, and thus padding can be added transparently).

**Comment by dstaesse** [comment]
Or just add mTU and MTU parameters to difconfigurations? Then the solution in the N+1 IPCP you suggest would be more simple to implement and indeed would not need changes in the shim.

**Comment by edugrasa** [comment]
The N DIF needs the MTU (maximum and minimum) info of the N-1 DIFs, agree. The shim Ethernet (our current one) cannot add/strip the padding because it doesn't have enough information (it can add the padding if the SDU is not encrypted, but it cannot remove it; and if the SDU is encrypted then it won't work). I was thinking in configuring the values as a simple solution for now, as you say. 

In the LLC case the Ethertype fields stores the length of the payload in the frame. In Linux this length field is not used to compute the length of the frame in the wire, therefore we could set it to be the length of the payload without the padding as you mention (and have transparent padding in the shim, which I agree it would be much better): http://www.embeddedlinux.org.cn/linux_net/0596002556/understandlni-CHP-13-SECT-5.html

So, should we wait for the LLC shim to be implemented and fix the padding issue there?

**Comment by dstaesse** [comment]
The length field of the Ethernet II header is always the data payload, excluding the padding. If length is < 46, padding is added until 46 bytes. We don't need to change anything. It will simply work ;)

**Comment by dstaesse** [comment]
With regard to your last question: adding mTU and MTU to the difconfigurations (for all DIFs, shims or normal) seems like something useful and not that hard to implement. 
The LLC shim may take a while to complete. 

So taking these two into account, I think implementing it now may make sense.
However, I prefer the N-DIF to pad for its own mTU. The reason being that doing it in the N+1 as you propose would mean that an N+1 AP on top of an N DIF with a low MTU would be responsible for padding. That doesn't make much sense to me.
So, another solution could be to only add the mTU to the normal IPCP and set the mTU of the 1-DIF to 46. This would make sure it pads everything enough and the VLAN shim will work. Once we have an LLC shim, we don't need the mTU for the 1-DIF.
