### ISSUE TITLE
remove useless "policies" from linux/net/rina/connection.h

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#420]
<a href="https://github.com/vmaffione"><img src="https://avatars.githubusercontent.com/u/4920001?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [vmaffione](https://github.com/vmaffione)**
_Thursday Nov 27, 2014 at 09:00 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/417_

----

The following three "policies" are unused, useless
 and duplicated - they already exist as function pointers
(dtc.c). They have to be removed here, and therefore
 from netlink (kernespace+userspace) and from librina. */

         struct policy *      initial_sequence_number;
         struct policy *      receiver_inactivity_timer;
         struct policy *      sender_inactivity_timer;

**Comment by sandervrijders** [comment]
Were they removed?

**Comment by sandervrijders** [comment]
@lbergesio Can this be closed?

**Comment by lbergesio** [comment]
These policies are not used, but it is the same case as in the dtcp_config. These are not policies as function pointers but strings to properly send the information from user space to the kernel in order to set the function pointers. They are not used because we can only select the policy set but not individual policies. I would not remove them now since the SDK will be changed and may be needed.

**Comment by edugrasa** [comment]
@lbergesio should these policies be removed or should we keep them? (just to close this issue :))

**Comment by edugrasa** [comment]
fixed by #866
