### ISSUE TITLE
General protection fault when sending sdu's over shim-tcp with logs disabled

### ISSUE THREAD

**Issue by kewinrausch** [IRATI/stack#424]
<a href="https://github.com/douwedb26"><img src="https://avatars.githubusercontent.com/u/6333903?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [douwedb26](https://github.com/douwedb26)**
_Wednesday Dec 03, 2014 at 15:40 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/421_

----

Dec  3 14:32:06 y kernel: [  525.029574] rina-kipcm: IPC Manager started. It is listening at NL port-id 1
Dec  3 14:33:01 y kernel: [  580.209250] general protection fault: 0000 [#4] SMP 
Dec  3 14:33:01 y kernel: [  580.209369] Modules linked in: shim_tcp_udp rina_personality_default nfsv3 iscsi_tcp libiscsi_tcp libiscsi scsi_transport_iscsi nfsd auth_rpcgss oid_registry nfs_acl nfs lockd fscache sunrpc psmouse i7core_edac ioatdma edac_core iTCO_wdt gpio_ich iTCO_vendor_support pcspkr lpc_ich serio_raw i2c_i801 tpm_tis hid_generic usbkbd usbmouse usbhid hid igb i2c_algo_bit dca ptp pps_core
Dec  3 14:33:01 y kernel: [  580.210709] CPU: 9 PID: 138 Comm: kworker/u52:0 Not tainted 3.15.0 #11
Dec  3 14:33:01 y kernel: [  580.210754] Hardware name: Supermicro X8DTT/X8DTT, BIOS 2.1b       10/28/2011
Dec  3 14:33:01 y kernel: [  580.210803] Workqueue: shim-tcp-udp tcp_udp_rcv_worker [shim_tcp_udp]
Dec  3 14:33:01 y kernel: [  580.210880] task: ffff8800b461b080 ti: ffff8800b4624000 task.ti: ffff8800b4624000
Dec  3 14:33:01 y kernel: [  580.210927] RIP: 0010:[<ffffffff81183e9d>]  [<ffffffff81183e9d>] __kmalloc+0x8d/0x180
Dec  3 14:33:01 y kernel: [  580.211010] RSP: 0018:ffff8800b4627cb8  EFLAGS: 00010286
Dec  3 14:33:01 y kernel: [  580.211053] RAX: 0000000000000000 RBX: 00000000000003e8 RCX: 00000000000021aa
Dec  3 14:33:01 y kernel: [  580.211098] RDX: 00000000000021a9 RSI: 0000000000000000 RDI: 0000000000015f60
Dec  3 14:33:01 y kernel: [  580.211144] RBP: ffff8800b4627cf8 R08: ffff8801b9cb5f60 R09: ffffffff816a8f32
Dec  3 14:33:01 y kernel: [  580.211189] R10: ffff8800301f9500 R11: 0000000000000002 R12: 3124191009040100
Dec  3 14:33:01 y kernel: [  580.211235] R13: 00000000000000d0 R14: 00000000000003e8 R15: ffff8801b9803500
Dec  3 14:33:01 y kernel: [  580.211281] FS:  0000000000000000(0000) GS:ffff8801b9ca0000(0000) knlGS:0000000000000000
Dec  3 14:33:01 y kernel: [  580.211328] CS:  0010 DS: 0000 ES: 0000 CR0: 000000008005003b
Dec  3 14:33:01 y kernel: [  580.211385] CR2: 00007effe7e76000 CR3: 0000000001c10000 CR4: 00000000000007e0
Dec  3 14:33:01 y kernel: [  580.211444] Stack:
Dec  3 14:33:01 y kernel: [  580.211494]  ffffffff816a8f32 ffffffffa025806e ffff88033796ad80 00000000000003e8
Dec  3 14:33:01 y kernel: [  580.211698]  0000000000000002 ffff8801b8797680 0000000000000000 ffff8801b9607700
Dec  3 14:33:01 y kernel: [  580.211901]  ffff8800b4627d18 ffffffff816a8f32 ffff88032973bae0 0000000000000002
Dec  3 14:33:01 y kernel: [  580.212105] Call Trace:
Dec  3 14:33:01 y kernel: [  580.212159]  [<ffffffff816a8f32>] ? rkmalloc+0x22/0x60
Dec  3 14:33:01 y kernel: [  580.212216]  [<ffffffffa025806e>] ? recv_msg+0x4e/0x50 [shim_tcp_udp]
Dec  3 14:33:01 y kernel: [  580.212275]  [<ffffffff816a8f32>] rkmalloc+0x22/0x60
Dec  3 14:33:01 y kernel: [  580.212332]  [<ffffffffa02586a9>] tcp_process_msg+0x1a9/0x580 [shim_tcp_udp]
Dec  3 14:33:01 y kernel: [  580.212392]  [<ffffffffa0258d83>] tcp_udp_rcv_worker+0x303/0x460 [shim_tcp_udp]
Dec  3 14:33:01 y kernel: [  580.212468]  [<ffffffff8106a61c>] process_one_work+0x17c/0x410
Dec  3 14:33:01 y kernel: [  580.212527]  [<ffffffff8106aa12>] worker_thread+0x122/0x370
Dec  3 14:33:01 y kernel: [  580.212585]  [<ffffffff8106a8f0>] ? process_scheduled_works+0x40/0x40
Dec  3 14:33:01 y kernel: [  580.212645]  [<ffffffff810718e9>] kthread+0xc9/0xe0
Dec  3 14:33:01 y kernel: [  580.212701]  [<ffffffff81071820>] ? flush_kthread_worker+0x80/0x80
Dec  3 14:33:01 y kernel: [  580.212761]  [<ffffffff816d5cec>] ret_from_fork+0x7c/0xb0
Dec  3 14:33:01 y kernel: [  580.212818]  [<ffffffff81071820>] ? flush_kthread_worker+0x80/0x80
Dec  3 14:33:01 y kernel: [  580.212876] Code: cd 00 00 49 8b 50 08 4d 8b 20 49 8b 40 10 4d 85 e4 0f 84 a7 00 00 00 48 85 c0 0f 84 9e 00 00 00 49 63 47 20 49 8b 3f 48 8d 4a 01 <49> 8b 1c 04 4c 89 e0 65 48 0f c7 0f 0f 94 c0 84 c0 74 b9 49 63 
Dec  3 14:33:01 y kernel: [  580.215103] RIP  [<ffffffff81183e9d>] __kmalloc+0x8d/0x180
Dec  3 14:33:01 y kernel: [  580.215192]  RSP <ffff8800b4627cb8>
Dec  3 14:33:01 y kernel: [  580.215299] general protection fault: 0000 [#5] SMP

**Comment by edugrasa** [comment]
Got a different one in pristine-1.4, still there.

----
 4790.410417] general protection fault: 0000 [#1] SMP 
[ 4790.414392] Modules linked in: shim_tcp_udp rina_default_plugin shim_eth_vlan rinarp arp826 nfsd auth_rpcgss oid_registry nfs_acl nfs lockd grace fscache sunrpc normal_ipcp 8021q garp stp llc psmouse serio_raw pcspkr i2c_piix4 hid_generic usbhid hid floppy
[ 4790.414392] CPU: 0 PID: 0 Comm: swapper/0 Not tainted 4.1.16 #50
[ 4790.414392] Hardware name: Xen HVM domU, BIOS 4.4.1 06/11/2015
[ 4790.414392] task: ffffffff81c12580 ti: ffffffff81c00000 task.ti: ffffffff81c00000
[ 4790.414392] RIP: 0010:[<ffffffff816b70cc>]  [<ffffffff816b70cc>] tcp_ack+0x50c/0x1350
[ 4790.414392] RSP: 0018:ffff88003be039b8  EFLAGS: 00210246
[ 4790.414392] RAX: 000000000000000a RBX: 0001001000000020 RCX: 0000000000000001
[ 4790.414392] RDX: ffff88002dd4ad80 RSI: ffffffffffffffff RDI: 0000000000000000
[ 4790.414392] RBP: ffff88003be03a58 R08: 0000000000000002 R09: ffff880000089130
[ 4790.414392] R10: 0000000000000000 R11: ffffea0000bfec00 R12: ffff880000089000
[ 4790.414392] R13: 0000000000004502 R14: 0000000000000000 R15: 00000000e883de28
[ 4790.414392] FS:  0000000000000000(0000) GS:ffff88003be00000(0000) knlGS:0000000000000000
[ 4790.414392] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[ 4790.414392] CR2: 0000000008446594 CR3: 000000002ffca000 CR4: 00000000001406f0
[ 4790.414392] Stack:
[ 4790.414392]  0000000000000000 ffff88003be183c0 ffff88003be039d8 ffff88002ffb2500
[ 4790.414392]  0000000000000000 ffff88003be17928 0000000000000000 ffffffffffffffff
[ 4790.414392]  0000000a00000000 ffffffffe883de98 000000000000000a 0000000a00000000
[ 4790.414392] Call Trace:
[ 4790.414392]  <IRQ> 
[ 4790.414392]  [<ffffffff816b843d>] tcp_rcv_established+0x19d/0x730
[ 4790.414392]  [<ffffffff8109a39d>] ? ttwu_do_wakeup+0x1d/0xe0
[ 4790.414392]  [<ffffffff816c3213>] tcp_v4_do_rcv+0x103/0x3e0
[ 4790.414392]  [<ffffffff8131adb6>] ? security_sock_rcv_skb+0x16/0x20
[ 4790.414392]  [<ffffffff816c486d>] tcp_v4_rcv+0x83d/0xa60
[ 4790.414392]  [<ffffffff8109d592>] ? default_wake_function+0x12/0x20
[ 4790.414392]  [<ffffffff810b1276>] ? autoremove_wake_function+0x16/0x40
[ 4790.414392]  [<ffffffff810b0bb5>] ? __wake_up_common+0x55/0x90
[ 4790.414392]  [<ffffffff8169d85e>] ip_local_deliver_finish+0xae/0x230
[ 4790.414392]  [<ffffffff8169db7a>] ip_local_deliver+0x4a/0xa0
[ 4790.414392]  [<ffffffff816c3fdc>] ? tcp_v4_early_demux+0x11c/0x170
[ 4790.414392]  [<ffffffff8169d4c8>] ip_rcv_finish+0x88/0x370
[ 4790.414392]  [<ffffffff8169de67>] ip_rcv+0x297/0x3b0
[ 4790.414392]  [<ffffffff8174bc7d>] ? packet_rcv_spkt+0x3d/0x170
[ 4790.414392]  [<ffffffff81663893>] __netif_receive_skb_core+0x843/0xa00
[ 4790.414392]  [<ffffffff81663a6a>] __netif_receive_skb+0x1a/0x80
[ 4790.414392]  [<ffffffff81663af3>] netif_receive_skb_internal+0x23/0x90
[ 4790.414392]  [<ffffffff81664768>] napi_gro_receive+0xc8/0x100
[ 4790.414392]  [<ffffffff8158a162>] xennet_poll+0xb22/0xbe0
[ 4790.414392]  [<ffffffff81663ffa>] net_rx_action+0x1fa/0x330
[ 4790.414392]  [<ffffffff81074ed1>] __do_softirq+0x111/0x280
[ 4790.414392]  [<ffffffff810751b5>] irq_exit+0x95/0xa0
[ 4790.414392]  [<ffffffff81471bc9>] xen_evtchn_do_upcall+0x39/0x50
[ 4790.414392]  [<ffffffff8178bc1e>] xen_hvm_callback_vector+0x6e/0x80
[ 4790.414392]  <EOI> 
[ 4790.414392]  [<ffffffff8105a0f6>] ? native_safe_halt+0x6/0x10
[ 4790.414392]  [<ffffffff8101e88e>] default_idle+0x1e/0xc0
[ 4790.414392]  [<ffffffff8101f46f>] arch_cpu_idle+0xf/0x20
[ 4790.414392]  [<ffffffff810b1987>] cpu_startup_entry+0x327/0x3f0
[ 4790.414392]  [<ffffffff817778bc>] rest_init+0x7c/0x80
[ 4790.414392]  [<ffffffff81d53f66>] start_kernel+0x43a/0x447
[ 4790.414392]  [<ffffffff81d53120>] ? early_idt_handler_array+0x120/0x120
[ 4790.414392]  [<ffffffff81d534d7>] x86_64_start_reservations+0x2a/0x2c
[ 4790.414392]  [<ffffffff81d5360f>] x86_64_start_kernel+0x136/0x145
[ 4790.414392] Code: 00 00 4c 39 cb 0f 84 88 0c 00 00 48 85 db 0f 84 7f 0c 00 00 49 3b 9c 24 70 02 00 00 0f 84 85 05 00 00 41 f6 84 24 49 02 00 00 02 <44> 0f b6 43 35 0f 85 61 09 00 00 41 8b 94 24 a8 05 00 00 3b 53 
[ 4790.414392] RIP  [<ffffffff816b70cc>] tcp_ack+0x50c/0x1350
[ 4790.414392]  RSP <ffff88003be039b8>
[ 4790.749660] ---[ end trace 9ad59f8f7ff35c71 ]---
[ 4790.753517] Kernel panic - not syncing: Fatal exception in interrupt
[ 4790.753610] Kernel Offset: disabled

**Comment by dstaesse** [comment]
yeah, what about disabling TCP and allow UDP only?

**Comment by edugrasa** [comment]
And another one over shim TCP, definitely it is not usable right now. Could not try with UDP since rina-tgen doesn't have the "-g" flag (if I try --qoscube unreliable it still picks TCP; with rina-echo-time -g 1 it picks UDP). But if  UDP works it may be an idea to drop TCP support and just a shim DIF over UDP.

----
[ 1638.877437] BUG: unable to handle kernel paging request at ffffffffffffffd8
[ 1638.881389] IP: [<ffffffff810904c0>] kthread_data+0x10/0x20
[ 1638.881389] PGD 1c0e067 PUD 1c10067 PMD 0 
[ 1638.881389] Oops: 0000 [#2] SMP 
[ 1638.881389] Modules linked in: rina_default_plugin shim_tcp_udp shim_eth_vlan rinarp arp826 nfsd auth_rpcgss oid_registry nfs_acl nfs lockd grace fscache sunrpc normal_ipcp 8021q garp stp llc psmouse serio_raw i2c_piix4 pcspkr hid_generic usbhid hid floppy
[ 1638.881389] CPU: 1 PID: 3173 Comm: kworker/u257:0 Tainted: G      D         4.1.16 #50
[ 1638.881389] Hardware name: Xen HVM domU, BIOS 4.4.1 06/11/2015
[ 1638.881389] task: ffff88002eba8000 ti: ffff88002dd90000 task.ti: ffff88002dd90000
[ 1638.881389] RIP: 0010:[<ffffffff810904c0>]  [<ffffffff810904c0>] kthread_data+0x10/0x20
[ 1638.881389] RSP: 0018:ffff88002dd93828  EFLAGS: 00210092
[ 1638.881389] RAX: 0000000000000000 RBX: 0000000000000001 RCX: 0000000000000000
[ 1638.881389] RDX: 000000000000000f RSI: 0000000000000001 RDI: ffff88002eba8000
[ 1638.881389] RBP: ffff88002dd93828 R08: 0000000000000000 R09: 0000000000000000
[ 1638.881389] R10: 0000000000001833 R11: ffff88002dd34a40 R12: 00000000000178c0
[ 1638.881389] R13: ffff88003be578c0 R14: ffff88002eba8000 R15: 0000000000000001
[ 1638.881389] FS:  0000000000000000(0000) GS:ffff88003be40000(0000) knlGS:0000000000000000
[ 1638.881389] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[ 1638.881389] CR2: 0000000000000028 CR3: 000000001e7cd000 CR4: 00000000001406e0
[ 1638.881389] Stack:
[ 1638.881389]  ffff88002dd93848 ffffffff8108aeb5 ffff88002dd93848 ffff88003be578c0
[ 1638.881389]  ffff88002dd93898 ffffffff81785429 0000000000000000 ffff88002eba8000
[ 1638.881389]  00000000000000eb ffff88002dd94000 ffff88002eba8788 ffff88002dd93468
[ 1638.881389] Call Trace:
[ 1638.881389]  [<ffffffff8108aeb5>] wq_worker_sleeping+0x15/0xa0
[ 1638.881389]  [<ffffffff81785429>] __schedule+0x7d9/0x9d0
[ 1638.881389]  [<ffffffff81785657>] schedule+0x37/0x90
[ 1638.881389]  [<ffffffff810727ed>] do_exit+0x73d/0xa80
[ 1638.881389]  [<ffffffff810172f8>] oops_end+0xa8/0x120
[ 1638.881389]  [<ffffffff810608dd>] no_context+0x11d/0x380
[ 1638.881389]  [<ffffffff81060bbd>] __bad_area_nosemaphore+0x7d/0x210
[ 1638.881389]  [<ffffffff81012713>] ? __switch_to+0x263/0x5d0
[ 1638.881389]  [<ffffffff81060d63>] bad_area_nosemaphore+0x13/0x20
[ 1638.881389]  [<ffffffff81061086>] __do_page_fault+0xc6/0x490
[ 1638.881389]  [<ffffffff81784fb3>] ? __schedule+0x363/0x9d0
[ 1638.881389]  [<ffffffff81061472>] do_page_fault+0x22/0x30
[ 1638.881389]  [<ffffffff8178be58>] page_fault+0x28/0x30
[ 1638.881389]  [<ffffffff8164b2b7>] ? lock_sock_nested+0x27/0x60
[ 1638.881389]  [<ffffffff81658699>] ? sk_stream_wait_memory+0x139/0x2e0
[ 1638.881389]  [<ffffffff8165862a>] ? sk_stream_wait_memory+0xca/0x2e0
[ 1638.881389]  [<ffffffff810b1260>] ? wait_woken+0x90/0x90
[ 1638.881389]  [<ffffffff816af1e2>] tcp_sendmsg+0x2a2/0xb10
[ 1638.881389]  [<ffffffff811c2712>] ? __free_slab+0xd2/0x1b0
[ 1638.881389]  [<ffffffff816da775>] inet_sendmsg+0x65/0xa0
[ 1638.881389]  [<ffffffff811c4e07>] ? __slab_free+0xa7/0x2c0
[ 1638.881389]  [<ffffffff8164818d>] sock_sendmsg+0x3d/0x50
[ 1638.881389]  [<ffffffff816482ab>] kernel_sendmsg+0x2b/0x30
[ 1638.881389]  [<ffffffffa01ce5c9>] send_msg+0x49/0x70 [shim_tcp_udp]
[ 1638.881389]  [<ffffffff81753979>] ? rkmalloc+0x19/0x50
[ 1638.881389]  [<ffffffffa01ce7c7>] tcp_udp_write_worker+0x1d7/0x2b7 [shim_tcp_udp]
[ 1638.881389]  [<ffffffff81089da8>] process_one_work+0x158/0x450
[ 1638.881389]  [<ffffffff8108a943>] worker_thread+0x73/0x560
[ 1638.881389]  [<ffffffff8108a8d0>] ? rescuer_thread+0x3b0/0x3b0
[ 1638.881389]  [<ffffffff8108fd8b>] kthread+0xdb/0x100
[ 1638.881389]  [<ffffffff8108fcb0>] ? kthread_create_on_node+0x180/0x180
[ 1638.881389]  [<ffffffff8178a362>] ret_from_fork+0x42/0x70
[ 1638.881389]  [<ffffffff8108fcb0>] ? kthread_create_on_node+0x180/0x180
[ 1638.881389] Code: 00 48 89 e5 5d 48 8b 40 c8 48 c1 e8 02 83 e0 01 c3 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 44 00 00 48 8b 87 18 05 00 00 55 48 89 e5 <48> 8b 40 d8 5d c3 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 44 00 00 
[ 1638.881389] RIP  [<ffffffff810904c0>] kthread_data+0x10/0x20
[ 1638.881389]  RSP <ffff88002dd93828>
[ 1638.881389] CR2: ffffffffffffffd8
[ 1638.881389] ---[ end trace 6e3036245e9c6ac5 ]---
[ 1638.881389] Fixing recursive fault but reboot is needed!

**Comment by edugrasa** [comment]
Fixd by #887
