### ISSUE TITLE
Use an sk_buff approach for PDUs

### ISSUE THREAD

**Issue by sandervrijders** [IRATI/stack#580]
Right now ser/des performs a lot of copies, which makes the stack consume a lot of memory under stress. Processing systems with not a lot of RAM even tend to run out.

**Comment by msune** [comment]
I couldn't agree more. +1

We have to start filling up the skb buffer from right to left, so that we can prepend N-1, N-2 etc.. PCIs without additional copies. We would therefore avoid scattered buffers, which is complex and much more complicated to optimize.

Once everything is more stable, we can think about memory mapping from user-space to kernel-space to even avoid the initial memory copy and the (expensive) per packet system call. But not now!

**Comment by edugrasa** [comment]
Fixed
