### ISSUE TITLE
pristine-1.3: create the directory for logs if the path doesn't exist upon install

### ISSUE THREAD

**Issue by dstaesse** [IRATI/stack#586]
When specifying the path for the config files in the ipcm configuration, the IPCM could check if the path exists and create the directories if necessary instead of reverting to stdout output.

**Comment by msune** [comment]
I don't get it; if the IPCM cannot find some config files, shouldn't it simply abort?

**Comment by sandervrijders** [comment]
I think Dimitri meant logPath instead of config files. Specifying the log path.

**Comment by sandervrijders** [comment]
@dstaesse Is this a required feature? How is this currently done by other UNIX daemons?

**Comment by nacarino** [comment]
@sandervrijders @dstaesse Having a daemon create directories is a dangerous proposition, especially if you are dealing with daemons with escalating permissions and having to change directory permissions. The most common practice, I have seen, is for the daemon to check if the required directories exist before actually executing. If a log directory is missing, you send the error to stderr, to a common syslog level or both so that the user knows what is going on. If what is missing is a configuration directory, then logging that to the daemos specific log is preferred.

**Comment by sandervrijders** [comment]
@nacarino I would tend to agree. However, if you install it sandboxed, maybe the build can create this path for you, as it already does for etc, bin, share, ...

**Comment by dstaesse** [comment]
@nacarino It is the /var/log/ directory, which usually exists in a system, but you are 100% right
The better solution is for the install to create them in the sandbox, as the install must be performed with the required root privileges.

**Comment by nacarino** [comment]
@sandervrijders I agree that something must create the required directories, but I don't think that is the job of the daemon. I agree with @dstaesse that it should be the install to create the directories should they not exist.

**Comment by sandervrijders** [comment]
@nacarino Yes, that's what I was saying as well.

**Comment by dstaesse** [comment]
@nacarino, @sandervrijders of course, that is something else than the logPath in the configuration file. If the directory in the logPath does not exist, we should indeed revert to stdout as the daemon is doing now.

**Comment by edugrasa** [comment]
Fixed by #893
