### ISSUE TITLE
dif-template-manager: remove hardcoded file names and extensions

### ISSUE THREAD

**Issue by vmaffione** [IRATI/stack#600]
These hardcoded things

https://github.com/IRATI/stack/blob/c932c86eff1661fd037536b44e888d5840f77591/rinad/src/ipcm/dif-template-manager.cc#L90-L99

have to go away.

If we have to resort to this approach to make things work it means that something is wrong in the approach - imho.

**Comment by edugrasa** [comment]
Well, we need to pass the name of the config file to the template manger (easy to do). 

The other ones I'm not so sure, since these are temporary files created by Linux when you edit the real file. It is garbage that must be ignored. Any approach for handling this in *Linux* (inotify is for Linux only anyway), in a more generic way?

**Comment by msune** [comment]
@vmaffione please use a more specific title for the issue.

@edugrasa what about only listing certain file extensions?

Btw, there is an important bug in the code that I missed; if a file is removed and someone had called previously:

https://github.com/IRATI/stack/blob/c932c86eff1661fd037536b44e888d5840f77591/rinad/src/ipcm/dif-template-manager.cc#L393

The `rinad::DIFTemplate *` object will be removed, and the application will (likely and hopefully) segfault, or corrupt memory otherwise.

The solution is to not expose the internal objects of the Template manager, so protecting it. Just return a list of handles, for instance std::string (copies) of the template name, and add an API call to return the template as a copy:

```
std::list<std::string> DIFTemplateManager::get_all_dif_templates();

//could also return a COPY of a DIFtemplate object.
std::string DIFTemplateManager::get(const std::string& name);
```


Sorry for not having seen it before.

**Comment by vmaffione** [comment]
I think this causes more problem than expected.
This is what happens when deploying configuration files in /etc/, like I normally do on my VMs.

````
320(1431951923)#ipcm (DBG): Starting main I/O loop...
320(1431951923)#ipcm.dif-template-manager (DBG): Found DIF template file called: default.dif
320(1431951923)#ipcm.dif-template-manager (DBG): Default DIF template found
320(1431951923)#ipcm.dif-template-manager (INFO): Added or modified DIF template called: default.dif
320(1431951923)#ipcm.dif-template-manager (DBG): Found DIF template file called: ssl
320(1431951923)#ipcm.conf (ERR): Failed to parse configuration
Failed to parse JSON
* Line 1, Column 1
  Syntax error: value, object or array expected.

320(1431951923)#ipcm.dif-template-manager (DBG): Found DIF template file called: dhcpcd.conf
320(1431951923)#ipcm.conf (ERR): Failed to parse configuration
Failed to parse JSON
* Line 1, Column 1
  Syntax error: value, object or array expected.

320(1431951923)#ipcm.dif-template-manager (DBG): Found DIF template file called: gshadow
320(1431951923)#ipcm.conf (ERR): Failed to parse configuration
Failed to parse JSON
* Line 1, Column 1
  Syntax error: value, object or array expected.

320(1431951923)#ipcm.dif-template-manager (DBG): Found DIF template file called: shells
320(1431951923)#ipcm.conf (ERR): Failed to parse configuration
Failed to parse JSON
* Line 1, Column 1
  Syntax error: value, object or array expected.

320(1431951923)#ipcm.dif-template-manager (DBG): Found DIF template file called: shadow.pacnew
320(1431951923)#ipcm.conf (ERR): Failed to parse configuration
Failed to parse JSON
* Line 1, Column 1
  Syntax error: value, object or array expected.

320(1431951923)#ipcm.dif-template-manager (DBG): Found DIF template file called: machine-id
ipcm: /home/vmaffione/irati/librina/src/jsoncpp/json_value.cpp:1065: const Json::Value& Json::Value::operator[](const char*) const: Assertion `type_ == nullValue || type_ == objectValue' failed.
````

We clearly need to filter only *.dif files.

**Comment by vmaffione** [comment]
(The IPCM crashes/aborts because of the failed assertion).

**Comment by edugrasa** [comment]
Ok, then the fix is to replace these lines https://github.com/IRATI/stack/blob/c932c86eff1661fd037536b44e888d5840f77591/rinad/src/ipcm/dif-template-manager.cc#L90-L99 with an if filename doesn't end in .dif, ignore
