### ISSUE TITLE
Upgrade to Linux kernel v. 4.1.x

### ISSUE THREAD

**Issue by edugrasa** [IRATI/stack#757]
Several reasons: support for gcc5, systemd >= 217, 3.15 is getting old, get new features and bug fixes

**Comment by msune** [comment]
I think it would be very useful to do several things along with this:

* Split repositories: use git submodules for kernel, librina and rinad and tools, and have an integration repository.
* Cleanup the history of the kernel subrepository. IOW, create a complete diff from the original kernel base as a single fat commit, and apply it directly to the vanilla kernel. E.g.: say it was 3.15.0, so apply a single patch on top of 3.15.0 before rebasing into 4.1.X. That would help when eventually we want to go mainstream.
* Prune history of the rest of repositories (librina, rinad); make subrepos smaller
* Keep the old all-in-one repo for consulting past history.

The current repo contains a lot of history of files that are not anymore there (e.g. wireshark dissector), plus a lot of history that is not relevant or bad formatted. This looks like a nice opportunity to do all this at once.

I can **actively** help on this, as I've done these sort of things before.

**Comment by vmaffione** [comment]
@marc thanks, you're offer to help is very much appreciated.

However, I don't think it's convenient to split right now. The main reason is instability of the APIs:
- librina and rinad are currently tightly coupled, and so they cannot be splitted before a very consistent refactory
- API between userspace and kernelspace (e.g. system calls, netlink messages) is evolving, very unstable, and so we would need atomic transactions on multiple repositories to avoid inconsistency. And, we definitely don't want to complicate our life with managing compatibilities (#ifdef) between different versions of userspace and kernelspace (e.g. new userspace, old kernelspace)
- we have to be honest, we are very far from the point we can discuss about mainstream.

I've never used git submodules, and to be honest I'm afraid it can be hard for the casual user - that is not git-submodules aware. Am I wrong?

Clean up the history seems appealing, but then we lose all the authorship of commits, don't know if we all contributors agree on that.

**Comment by msune** [comment]
@vmaffione 

>librina and rinad are currently tightly coupled, and so they cannot be splitted before a very consistent refactory

The build systems are clearly separated and the headers and libraries are correctly distributed. Don't agree

>API between userspace and kernelspace (e.g. system calls, netlink messages) is evolving, very unstable, and so we would need atomic transactions on multiple repositories to avoid inconsistency. And, we definitely don't want to complicate our life with managing compatibilities (#ifdef) between different versions of userspace and kernelspace (e.g. new userspace, old kernelspace)

The commits on the sub-repos may evolve but someone who is downloading the integration repository would have a consistent set of commits of the sub-repos (even  more as of now if correctly done).

In short, every submodule points to a single commit. Parent repository tracks the exact commit, and you can change these pointers in a single commit (hence transactional).

That means that if we would have something like (in the integration repository):

* kernel  -> commit SHA1 A (on kernel repository)
* librina  -> commit SHA1 B (on librina repository)
* rinad   -> commit SHA1 C (on rinad repository)

Histories of the 3 components would be split. Pull requests would go to the individual repositories, and 1 (single one) to the integration repository. If a patch touches kernel and librina, then you would have:

* PR to kernel
* PR to librina
* PR to the integration, pointing submodules to commit A' and B'

Ideally the 3 PRs shall be integrated at once (but in order). IN any case, if the 2 first PR are integrated before, the users using the integration repository would not see this (unless manually fetched and checkout), so that's good.

It is a bit more of overhead, but I think it pays off (it did for us in the past)

>we have to be honest, we are very far from the point we can discuss about mainstream.

Fair, but to me, we need to start the cleanup.

I recommend to play a bit with git submodules. It is pretty easy.
