### ISSUE TITLE
Update tutorials wiki page to current IPCM configuration file

### ISSUE THREAD

**Issue by vmaffione** [IRATI/stack#889]
Current tutorials are outdated, since they don't make use of DIF templates.
Moreover, the configruation needs UNIX sockets right now.

**Comment by jmuchemb** [comment]
I have started to update the wiki. I've pushed changes in my fork:
  https://github.com/jmuchemb/irati-stack/wiki
- The IPCM console now uses UNIX socket instead of TCP
- Home: Wireshark fork has been moved to a separate repository

I wanted to replace all absolute urls (https://github.com/IRATI/stack/...) by relative urls but without success, since that does not work well on GitHub:
- image urls behave differently than other
- this breaks preview
- the Home url is .../wiki whereas other are .../wiki/foo

So navigating through https://github.com/jmuchemb/irati-stack/wiki is difficult.

**Comment by edugrasa** [comment]
Update done!
