### ISSUE TITLE
configure script for librina/rinad/rina-tools does not accept custom CFLAGS

### ISSUE THREAD

**Issue by vmaffione** [IRATI/stack#890]
This prevents build from stripping symbols and enable -O2 optimizations.

**Comment by vicalro** [comment]
I found some time ago that even if the configuration option --enable-debug is given, the flag -O0 is added but the -O2 stays there (and the last one is the valid one in that case). The problem is in this lines of configure.ac:

https://github.com/IRATI/stack/blob/894b7d8703c5e18a605bafa030c72ff29207c6bf/librina/configure.ac#L89-104

Let me investigate it further and come with a fix.

**Comment by vicalro** [comment]
So the problem seems to be that in the line:
https://github.com/IRATI/stack/blob/894b7d8703c5e18a605bafa030c72ff29207c6bf/librina/configure.ac#L93

We want to test if CXXFLAGS contain the -O2 flag; but there are two mistakes.

- The first one is that the ticks execute the echo + grep command, but the returned string is being executed afterwards by AS_IF
- The second one is that the grep is not properly backslashing the minus sign, so the pattern `-O2` is not being detected.

The result is that even if the debugging flags (-O0 -g -fno-inline) are set in the CXXFLAGS_EXTRA the original -O2 is not stripped and its added after the debugging ones.

I will send a PR soon with the fix.
