### ISSUE TITLE
Installation and Implementation of Prototype IRATI in Testbed FIBRE

### ISSUE THREAD

**Issue by DjalmaFilho-UFPE** [IRATI/stack#901]
Dear friends,

I'm trying to implement the prototype IRATI experimentation network FIBRE - https://fibre.org.br/, but I have problem when you finish the installation of the prototype. Because virtual machines are paravirtualized on XEN environment would like to know if there is any restriction to this environment, ie paravirtualizadas virtual machines on XEN. You can prototype installation in **paravirtualizadas virtual machines on XEN**?

**Comment by edugrasa** [comment]
We are running the prototype in fully-virtualized XEN VMs that use paravirtualized drivers. Not sure if something specific has to be done for paravirtualized VMs.. @lbergesio knows more about this environment, he may be able to provide more hints!

**Comment by DjalmaFilho-UFPE** [comment]
Thank you! I'll check with @lbergesio.

**Comment by lbergesio** [comment]
Hi @DjalmaFilho-UFPE . I am not sure If I get your question. Running the IRATI stack in a paravirtualized VM is not possible since you need to install a custom kernel with the RINA implementation. Last versions of the OCF (OFELIA Control Framework) supported the creation of VMs based on a dedicated IRATI template using full virtualization. Does this solve your question?

**Comment by DjalmaFilho-UFPE** [comment]
Resolves yes @bergesio. Thank you so much!
